### PR TITLE
Rename and document the test script and print elapsed time

### PR DESCRIPTION
**Pull request by stefanrueger**

### CODE REVIEW

**Comment by stefanrueger** [comment]
Now the output looks like so
```
$ test-avrdude -d0 -p"-cdryrun -pATxmega64D4"
Testing avrdude version 7.2-20231218 (62b15d20)
Prepare "-cdryrun -pATxmega64D4" and press 'enter' or 'space' to continue. Press any other key to skip
✅   0.000 s: set, clear and read eesave fuse bit
✅   0.072 s: the_quick_brown_fox_69632B.hex flash -U write/verify
✅   0.068 s: the_quick_brown_fox_2048B.hex eeprom -U write/verify
✅   0.072 s: lorem_ipsum_69632B.srec flash -U write/verify
✅   0.069 s: lorem_ipsum_2048B.srec eeprom -U write/verify
✅   0.069 s: 0xff_2048B.hex eeprom -U write/verify
✅   0.069 s: the_quick_brown_fox_69632B.hex:a flash -T write/verify
✅   0.069 s: the_quick_brown_fox_2048B.hex:a eeprom -T write/verify
✅   0.069 s: lorem_ipsum_69632B.srec flash -T write/verify
✅   0.069 s: lorem_ipsum_2048B.srec eeprom -T write/verify
✅   0.069 s: cola-vending-machine.raw flash -T/-U write/verify
✅   0.068 s: holes_pack_my_box_69632B.hex:a flash -U write
✅   0.068 s: holes_the_five_boxing_wizards_69632B.hex flash -T write
✅   0.068 s: holes_pack_my_box_2048B.hex:a eeprom -U write
✅   0.068 s: holes_the_five_boxing_wizards_2048B.hex eeprom -T write
✅   0.068 s: random_data_256B.bin usersig -T/-U write/read
```

Some of the tests seem to be repetitive, so the script could probably do with slimming down the number of tests. That is best done by @MCUdude and @mcuee as you have the programmers and parts, so you will know how big your *pain threshold* is for waiting for the tests to finish. Also, once we have dealt with the causes of [test failure by calling successive AVRDUDE calls too fast](https://github.com/avrdudes/avrdude/issues/1632) we can set the default for the pesky `delay` parameter to 0.

**Comment by stefanrueger** [comment]
Fixes #12 and #4.

**Comment by MCUdude** [comment]
Neat, thank you!

> Some of the tests seem to be repetitive, so the script could probably do with slimming down the number of tests. That is best done by @MCUdude and @mcuee as you have the programmers and parts, so you will know how big your pain threshold is for waiting for the tests to finish. 

The idea was to test several files and flipping 0's into 1's in both the EEPROM and flash memory. It would be great if you could point out what we could remove. Running the test script using a  USBtinyISP programmer and an ATmega2560 took almost an hour. It did pass the test, but it was indeed painful.

> Also, once we have dealt with the causes of test failure by calling successive AVRDUDE calls too fast we can set the default for the pesky delay parameter to 0.

I plan to find the necessary delay for various programmers this week. I just received a new/used AVR Dragon in the mail yesterday, as my old one got unstable. The Dragon is probably the worst in its class. It would be interesting to know if the JTAGmkII had the same issues...

**Comment by stefanrueger** [comment]
> took almost an hour

Yes, this needs slimming down. I'll think about how that can be done. In the first instance `-U memory:v:...` can be removed as in absence of `-V` the preceding `-U memory:w:...` will already carry out a verify. Maybe we only write *one* file per memory with holes and only if that fails do another test writing the full memory from 0. Checking whether 0s can be flipped to 1s can be done with a simpler `-U eeprom:w:0x55:m -U eeprom:w:0xaa:m` (one byte is enough) and that test can be named "flip 0 to 1".

**Comment by mcuee** [comment]
Quite nice.

The following is under NetBSD 9.3.
```
-bash-5.2$ ./test-avrdude -p "-c usbasp -p m328pb"
Testing avrdude version 7.2-20240122 (2f89aece)
Prepare "-c usbasp -p m328pb" and press 'enter' or 'space' to continue. Press any other key to skip
✅   0.000 s: set, clear and read eesave fuse bit
✅  11.592 s: the_quick_brown_fox_32768B.hex flash -U write/verify
✅  11.221 s: the_quick_brown_fox_1024B.hex eeprom -U write/verify
✅  11.591 s: lorem_ipsum_32768B.srec flash -U write/verify
✅  11.211 s: lorem_ipsum_1024B.srec eeprom -U write/verify
✅  11.361 s: 0xff_1024B.hex eeprom -U write/verify
✅  11.361 s: the_quick_brown_fox_32768B.hex:a flash -T write/verify
✅  11.361 s: the_quick_brown_fox_1024B.hex:a eeprom -T write/verify
✅  11.361 s: lorem_ipsum_32768B.srec flash -T write/verify
✅  11.361 s: lorem_ipsum_1024B.srec eeprom -T write/verify
✅  11.361 s: cola-vending-machine.raw flash -T/-U write/verify
✅   3.194 s: holes_pack_my_box_32768B.hex:a flash -U write
✅   3.194 s: holes_the_five_boxing_wizards_32768B.hex flash -T write
✅   2.977 s: holes_pack_my_box_1024B.hex:a eeprom -U write
✅   2.977 s: holes_the_five_boxing_wizards_1024B.hex eeprom -T write
```

And OpenBSD 7.4.
```
openbsd74$ ./test-avrdude -p "-c usbasp -p m328pb"
Testing avrdude version 7.2-20240122 (2f89aece)
Prepare "-c usbasp -p m328pb" and press 'enter' or 'space' to continue. Press any other key to skip
✅   0.000 s: set, clear and read eesave fuse bit
✅  11.675 s: the_quick_brown_fox_32768B.hex flash -U write/verify
✅  11.089 s: the_quick_brown_fox_1024B.hex eeprom -U write/verify
✅  11.674 s: lorem_ipsum_32768B.srec flash -U write/verify
✅  11.087 s: lorem_ipsum_1024B.srec eeprom -U write/verify
✅  11.300 s: 0xff_1024B.hex eeprom -U write/verify
✅  11.300 s: the_quick_brown_fox_32768B.hex:a flash -T write/verify
✅  11.300 s: the_quick_brown_fox_1024B.hex:a eeprom -T write/verify
✅  11.300 s: lorem_ipsum_32768B.srec flash -T write/verify
✅  11.300 s: lorem_ipsum_1024B.srec eeprom -T write/verify
✅  11.300 s: cola-vending-machine.raw flash -T/-U write/verify
✅   3.312 s: holes_pack_my_box_32768B.hex:a flash -U write
✅   3.312 s: holes_the_five_boxing_wizards_32768B.hex flash -T write
✅   3.043 s: holes_pack_my_box_1024B.hex:a eeprom -U write
✅   3.043 s: holes_the_five_boxing_wizards_1024B.hex eeprom -T write
```

**Pull request merged**
