### PR TITLE
Add dryrun tests

### PR DESCRIPTION
**Pull request by stefanrueger**
These high-level, programmer-independent tests are being done for "-cdryrun -pm2560" only.

This concludes what I can do for the test-avrdude script (except obvsly fixing errors in the script).

Of course, some of the detected errors are limitations of the programmer/bootloader, and not of AVRDUDE, but that is useful to know and document(!) too. 

Pro tip: Currently, AVRDUDE simply *ignores* non-options on the command line. You can utilise this to add extra descriptions into the test strings, eg, when you test different bootloaders for the *same* `-c` programmer and `-p` part like so:
```
test-avrdude -p "-curclock -pm328p Optiboot 4.4" \
             -p "-curclock -pm328p urboot 7.7 weu-jPrac" 
```
The test script will ask to `Prepare "-curclock -pm328p urboot 7.7 weu-jPrac" ...' ` and the output is *self-documenting*

So, @MCUdude @mcuee @askn37 @dl8dtl @dbuchwald happy testing, exploring, bug fixing and documenting. I am away from my usual environment without AVRs :open_mouth: without programmers :open_mouth: - I know: hard life!

### CODE REVIEW

**Comment by mcuee** [comment]
@stefanrueger 

Actually I test `dryrun` quite extensively previously across different platforms -- basically I change all the following no `dryrun` programmer listed with `-cdryrun`. (Note: need to remover `-r` for Nano Every).

```
if [[ ${#pgm_and_target[@]} -eq 0 ]]; then
  # Default tests in absence of -p
  pgm_and_target+=(
    "-cdryrun -pm328p"
    "-cdryrun -px64a1"
    "-cpkobn_updi -B1 -patmega3208"
    "-cpkobn_updi -B1 -patmega3209"
    "-cpkobn_updi -B1 -patmega4808"
    "-cjtag2updi -patmega4809 -Pusb:2341:0058 -r"
    "-cpkobn_updi -B1 -pattiny3217"
    "-cpkobn_updi -B1 -pavr128da48"
    "-cpkobn_updi -B1 -pavr128db48"
    "-cpkobn_updi -B1 -pavr64dd32"
    "-cpkobn_updi -B1 -pavr64ea48"
    "-cpkobn_updi -B1 -pavr16eb32"
    "-cxplainedmini_isp -patmega328pb"
    "-cxplainedmini_updi -pattiny1616"
    "-cxplainedmini_updi -pattiny3217"
    "-cxplainedpro_updi -B1 -pattiny817"
    "-cxplainedpro_pdi -B0.5 -patxmega128a1u"
    "-cxplainedpro -B4MHz -patmega256rfr2"
  )
fi
```

**Comment by mcuee** [comment]
@stefanrueger 

Of course this is still a good change to have.

**Comment by stefanrueger** [comment]
@mcuee You are mistaken, this PR adds real tests that are only triggered when the `-cdryrun -pm2560` test is run; these are high-level tests of some of fileio logic in AVRDUDE that are independent of any programmer and provide further sanity checking. Hence, I consider these useful to have in the overall test script.

**Comment by mcuee** [comment]
> @mcuee You are mistaken, this PR adds real tests that are only triggered when the `-cdryrun -pm2560` test is run; these are high-level tests of some of fileio logic in AVRDUDE that are independent of any programmer and provide further sanity checking. Hence, I consider these useful to have in the overall test script.

Yes I agree. I did not mentioned this clearly in the early reply.

**Comment by mcuee** [comment]
The newly added tests are very nice. It will be good to add one for xmega and one for UPDI part.
```
mcuee@mcuees-Mac-mini avrdude-test-script_sr % ./test-avrdude 
Testing avrdude version 7.2-20240122 (2f89aece)
Prepare "-cdryrun -pm2560" and press 'enter' or 'space' to continue. Press any other key to skip
✅   0.098 s: flash raw format -T/-U write/verify cola-vending-machine.raw
✅   0.091 s: flash extended address and hole test
✅   0.118 s: flash writing binary numbers
✅   0.139 s: flash reading and verifying binary numbers
✅   0.124 s: flash writing octal numbers
✅   0.149 s: flash reading and verifying octal numbers
✅   0.116 s: flash writing decimal numbers
✅   0.151 s: flash reading and verifying decimal numbers
✅   0.117 s: flash writing hexadecimal numbers
✅   0.120 s: flash reading and verifying hexadecimal numbers
✅   0.109 s: flash writing R numbers
✅   0.135 s: flash reading and verifying R numbers
✅   0.108 s: flash writing srec format
✅   0.092 s: flash reading and verifying srec format file
✅   0.090 s: fuse access: clear, set and read eesave fuse bit
✅   0.090 s: fuse access: set eesave fusebit to delete EEPROM on chip erase
✅   0.090 s: chip erase
✅   0.093 s: flash -U write/verify holes_rjmp_loops_262144B.hex
✅   0.094 s: flash -T write/verify holes_rjmp_loops_262144B.hex
✅   0.090 s: eeprom check whether programmer can flip 0s to 1s
✅   0.057 s: eeprom -U write/verify holes_pack_my_box_4096B.hex
✅   0.092 s: eeprom -T write/verify holes_{the_five_boxing_wizards,pack_my_box}_4096B.hex
✅   0.098 s: chip erase and spot check flash is actually erased
✅   0.096 s: spot check eeprom is erased, too
```

**Comment by MCUdude** [comment]
Thanks!

**Pull request merged**
